name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'  # Запуск каждый день в 3:00 UTC
  workflow_dispatch:     # Возможность запуска вручную через интерфейс

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get upstream repository URL
        id: get-upstream
        run: |
          repo_json=$(gh api repos/${{ github.repository }})
          upstream_url=$(echo "$repo_json" | jq -r '.parent.clone_url // ""')
          if [ -z "$upstream_url" ]; then
            echo "This is not a fork. Skipping."
            exit 0
          fi
          echo "upstream_url=$upstream_url" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote
        if: steps.get-upstream.outputs.upstream_url != ''
        run: git remote add upstream "${{ steps.get-upstream.outputs.upstream_url }}"

      - name: Fetch upstream
        if: steps.get-upstream.outputs.upstream_url != ''
        run: git fetch upstream

      - name: Merge upstream into fork (favor upstream)
        if: steps.get-upstream.outputs.upstream_url != ''
        run: |
          git checkout ${{ github.event.repository.default_branch }}
          git fetch upstream
          git merge -X theirs upstream/${{ github.event.repository.default_branch }} --no-edit || echo "Merge conflict"
          git push origin ${{ github.event.repository.default_branch }}
