name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'  # Запуск каждый день в 3:00 UTC
  workflow_dispatch:     # Возможность запуска вручную через интерфейс

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # важно: чтобы git знал всю историю

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get upstream repository URL
        id: get-upstream
        run: |
          repo_json=$(gh api repos/${{ github.repository }})
          upstream_url=$(echo "$repo_json" | jq -r '.parent.clone_url // ""')
          if [ -z "$upstream_url" ]; then
            echo "This is not a fork. Skipping."
            exit 0
          fi
          echo "upstream_url=$upstream_url" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote
        if: steps.get-upstream.outputs.upstream_url != ''
        run: git remote add upstream "${{ steps.get-upstream.outputs.upstream_url }}"

      - name: Fetch upstream
        if: steps.get-upstream.outputs.upstream_url != ''
        run: git fetch upstream

      - name: Merge upstream into fork (keep your changes)
        if: steps.get-upstream.outputs.upstream_url != ''
        run: |
          BRANCH="${{ github.event.repository.default_branch }}"
          git checkout "$BRANCH"
          git merge upstream/"$BRANCH" --allow-unrelated-histories --no-edit || echo "⚠️ Merge conflict — requires manual resolution"
          git push origin "$BRANCH"
